---
- name: Bootstrap Pi media prerequisites
  hosts: pis
  become: true
  vars_files:
    - ../inventory/group_vars/vault.yml
  roles:
    - role: system_prep
    - role: mounts
    - role: folders
    - role: docker_engine
    - role: compose_deploy
    - role: mount_guard
    - { role: tailscale, when: tailscale_auth_key is defined }
    - role: samba_shares
    - role: app_extras
