# Global variables shared across all Raspberry Pis
# Non-sensitive defaults

# System
timezone: Europe/London
main_user: holly
main_group: holly
puid: 1000
pgid: 1000

# Storage devices (use actual UUIDs for real deployments)
storage_device_uuid: "UUID-OF-STORAGE-DRIVE"
storage_mount_point: "/mnt/storage"
storage_fs: auto

# Downloads device
downloads_device_uuid: "UUID-OF-DOWNLOADS-DRIVE"
downloads_mount_point: "/mnt/downloads"
downloads_fs: auto

# Mount options
mount_opts_ext4: "defaults,noatime"
mount_opts_ntfs: "defaults,uid={{ puid }},gid={{ pgid }},umask=002"

# Folder structure under storage/downloads
media_root: "/mnt/storage"
media_dirs:
  - Movies
  - TVShows
  - music
  - podcasts
  - books
  - audiobooks

downloads_root: "/mnt/downloads"
downloads_dirs:
  - completed
  - incomplete
  - getiplayer

# Root directory for all Docker configs and compose files
mediastack_root: "/opt/mediastack"

# Optional hostname configuration
set_hostname: false
hostname_value: "pi-media"

# Explicit mapping of mounts and hosted folders
mount_map:
  - name: downloads
    mount_point: "/mnt/downloads"
    uuid: "{{ downloads_device_uuid }}"
    fstype: "{{ downloads_fs }}"
    folders:
      - path: "/mnt/downloads"
        ensure: true
      - path: "/mnt/downloads/getiplayer"
        ensure: true
      - path: "/mnt/downloads/completed"
        ensure: true
  - name: storage
    mount_point: "/mnt/storage"
    uuid: "{{ storage_device_uuid }}"
    fstype: "{{ storage_fs }}"
    folders:
      - path: "/mnt/storage/Movies"
        ensure: true
      - path: "/mnt/storage/TVShows"
        ensure: true
      - path: "/mnt/storage/music"
        ensure: true
      - path: "/mnt/storage/podcasts"
        ensure: true
      - path: "/mnt/storage/books"
        ensure: true
      - path: "/mnt/storage/audiobooks"
        ensure: true

# Backups
backups_device_uuid: "UUID-OF-BACKUPS-DRIVE"
backups_mount_point: "/mnt/backups"
backups_fs: auto
backup_keep_daily: 7
backup_keep_weekly: 4
backup_mirror_dir: "{{ mediastack_root }}/backups"
backup_healthcheck_url: ""
backup_timer_on_calendar: "daily"

# Watchtower
watchtower_schedule: "0 4 * * *"
# watchtower_notification_url: ""

# Monitoring
cadvisor_port: 8082

# Docker Images and Ports
gluetun_image: "qmcgaw/gluetun:latest"
requestrr_image: "thomst08/requestrr:latest"
jackett_image: "linuxserver/jackett:latest"
sonarr_image: "linuxserver/sonarr:latest"
radarr_image: "linuxserver/radarr:latest"
lidarr_image: "lscr.io/linuxserver/lidarr:latest"
transmission_image: "linuxserver/transmission:latest"
rdtclient_image: "rogerfar/rdtclient"
sabnzbd_image: "lscr.io/linuxserver/sabnzbd:latest"
get_iplayer_image: "ghcr.io/thespad/get_iplayer:latest"
lazylibrarian_image: "linuxserver/lazylibrarian:latest"
audiobookshelf_image: "ghcr.io/advplyr/audiobookshelf:latest"
navidrome_image: "deluan/navidrome:latest"
jellyfin_image: "linuxserver/jellyfin:latest"
pi_health_dashboard_image: "brownster/pi-health:latest"
watchtower_image: "containrrr/watchtower:latest"

vpn_port_9117: 9117
vpn_port_8989: 8989
vpn_port_7878: 7878
vpn_port_9091: 9091
vpn_port_6789: 6789
vpn_port_6500: 6500
vpn_port_8686: 8686
vpn_port_8080: 8080
requestrr_port_4545: 4545
get_iplayer_port_1935: 1935
lazylibrarian_port_5299: 5299
audiobookshelf_port_13378: 13378
navidrome_port_4533: 4533
jellyfin_port_8096: 8096
jellyfin_port_8920: 8920
pi_health_dashboard_port_8100: 8100
